### ISSUE TITLE
Appliance used

### ISSUE THREAD

**Issue by tev-oo** [NGMunia/OSPFv3#1]
Hello, which appliance did you use on GNS3 to send your scripts to the routers? Because I encountered issues using the Network Automation Appliance.

**Comment by NGMunia** [comment]
Used Ubuntu Virtual machine with visual code installed. But make sure you install libraries. You can also use Windows vm

**Comment by NGMunia** [comment]
You can also use Windows VM

**Comment by tev-oo** [comment]
Ok thanks, I'll run using Ubuntu.

**Comment by tev-oo** [comment]
Hello,
Anthony can help troubleshoot a network issue?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/06/23,
08:52:31 AM

**Comment by NGMunia** [comment]
WHICH?

**Comment by tev-oo** [comment]
It is not this lab, but for example I have a router that currently has a
public IP assigned to it by the ISP. I want too add another ISP as
backup for redundancy. How  should I go about doing this?

**Comment by NGMunia** [comment]
Use a floating static pointing to the backup ISP (default route with a higher AD)

**Comment by NGMunia** [comment]
Example:

Ip route 0.0.0.0.0.0 0.0.0.0 <ip address of isp1>
Ip route 0.0.0.0 0.0.0.0  <ip address of isp2> 10

10 is AD

**Comment by NGMunia** [comment]
You can also incorporate IPSLA with object tracking for automatic switchover to the backup  isp should the internet not be reachable via the main isp

**Comment by tev-oo** [comment]
IPSLA Ok I will check this out, What about using the BGP protocol

**Comment by NGMunia** [comment]
If connectivity is used for basic Internet connection e.g browsing no need usingBGP. Use static routes, but if you are offering services in your organization for which need to be accessed via Internet, e.g hosting Web servers  for clients then you need BGP.

**Comment by tev-oo** [comment]
So find a way to set up static routes on the edge router instead of using
BGP
Ok can we continue on this thread or you can send me your email address



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/07/23,
10:28:53 AM

**Comment by NGMunia** [comment]
melvinoxl7@gmail.com

**Comment by NGMunia** [comment]
Sample config: cisco router

Ipsla:
 This is used to test reachability of a destination address by use of but not limited to icmp probes.

Example on your main isp connection:

Ip sla 1 
Icmp-echo (destination-ip) source-ip (your ip add)
Ip sla schedule start-time now lifetime forever 
(This command will send icmp probes always)

Then you can associate this sla configuration with object tracking.
Object tracking will aid in switch-over 

Commands:
Track 1 ip sla 1
Delay up 10 down 10

(The command delay up 10 down 10 means that if the link goes down/up, the router will wait for 10 seconds before switching. This takes care of link flaps to prevent instability or frequent changeovers)


Ip route  0.0.0.0 0.0.0.0 (isp1-gateway) track 1
Ip route  0.0.0.0 0.0.0.0 (isp2-gateway) 10

The second static route (floating static) has a higher AD therefore its not added in the routing table.

The first has a lower AD and is in the routing table but this is dependent on the Object track configured
